--- #YAML:1.0
name:               distlinks
version:            2
abstract:           URL link checking with database.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:         0
    Class::Singleton:     0
    constant::defer:      0
    DBD::SQLite:          0
    DBI:                  0
    File::chdir:          0
    File::Find::Iterator:  0
    File::HomeDir:        0
    File::Type:           0
    HTML::Entities:       0
    HTML::Parser:         0
    Image::ExifTool:      0
    IO::String:           0
    Iterator::Simple:     0
    List::MoreUtils:      0
    Locale::TextDomain:   0
    LWP:                  5.819
    LWP::Debug:           0
    perl:                 5.010
    Perl6::Slurp:         0
    Regexp::Common:       0
    Regexp::Common::URI::RFC2396:  0
    URI:                  0
    URI::Escape:          0
    URI::file:            0
    URI::Find:            0
    WWW::Mechanize:       0
    YAML:                 0
resources:
    homepage:  http://user42.tuxfamily.org/distlinks/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - junk
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
optional_features:
    maximum_devel:
        description:  Stuff used variously for development.
        requires:
            Devel::FindRef:    0
            Devel::Peek:       0
            File::MMagic:      0
            LWP::UserAgent:    0
            warnings::unused:  0
    maximum_tests:
        description:  Have "make test" do as much as possible.
        requires:
            Parse::CPAN::Meta:   0
            Test::DistManifest:  0
            Test::Pod:           1.00
            Test::Synopsis:      0
            Test::YAML::Meta:    0.15
            YAML:                0
            YAML::Syck:          0
            YAML::Tiny:          0
            YAML::XS:            0
