--- #YAML:1.0
name:               distlinks
version:            8
abstract:           URL link checking with database.
author:
    - Kevin Ryde <user42@zip.com.au>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Archive::Zip:         0
    Class::Singleton:     0
    constant::defer:      0
    DBD::SQLite:          0
    DBI:                  0
    File::chdir:          0
    File::Find::Iterator:  0
    File::HomeDir:        0
    File::Type:           0
    HTML::Entities:       0
    HTML::Parser:         0
    HTTP::Date:           0
    HTTP::Response:       0
    HTTP::Status:         0
    Image::ExifTool:      0
    IO::String:           0
    Iterator::Simple:     0
    List::MoreUtils:      0.24
    Locale::TextDomain:   0
    LWP:                  5.819
    LWP::Debug:           0
    Module::Util:         0
    perl:                 5.010
    Perl6::Slurp:         0
    Regexp::Common:       0
    Regexp::Common::URI::RFC2396:  0
    URI:                  0
    URI::Escape:          0
    URI::file:            0
    URI::Find:            0
    WWW::Mechanize:       0
    YAML:                 0
resources:
    homepage:  http://user42.tuxfamily.org/distlinks/index.html
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
        - devel
        - xt
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
